### ISSUE TITLE
One question about code/evaluation/packed_dataset.py

### ISSUE THREAD

**Issue by jiangh0** [hkust-nlp/llm-compression-intelligence#3]
I have a little question about code/evaluation/packed_dataset.py.
In this file, `self.raw_datase` has filtered from `self._raw_dataset`. Why does `self.data` still uses `self._raw_dataset` to process?

```
        self.raw_dataset = self._raw_dataset.filter(lambda example: len(example['content']) > 0)
        self.character_num = 0
        for i in range(len(self.raw_dataset)):
            self.character_num += len(self.raw_dataset[i]['content'])
        self.data = self._raw_dataset.map(
            lambda example: {"encoding": np.array(self.tokenizer.encode(example['content']), dtype=self._dtype)}, num_proc=8)
```

**Comment by jiangh0** [comment]
another question
How long do you get the github corpus used in paper?

**Comment by HYZ17** [comment]
Thank you for your feedback
1. This is a bug. We will fix it.
2. If you are asking about the time it takes to collect GitHub Corpus, it depends on your internet speed. The time we spent was approximately half a day.

**Comment by jiangh0** [comment]
Is there code about  `MIN-K% PROB` in this repo? I didn't find it.
Can you open source this part of the code? Perhaps tell the way you use in your paper.

**Comment by jinghan23** [comment]
We plan to open source this part of code later. You can also refer to [github repo](https://github.com/swj0419/detect-pretrain-code) of [Detecting Pretraining Data from Large Language Models](https://arxiv.org/pdf/2310.16789.pdf) for Min-K% Prob code because we are using their method.
