### ISSUE TITLE
Question about min-k%

### ISSUE THREAD

**Issue by jiangh0** [hkust-nlp/llm-compression-intelligence#4]
![image](https://github.com/hkust-nlp/llm-compression-intelligence/assets/24559732/0a37966d-ae48-485c-be52-9fae7ee2e851)

How to explain this pic? 

1. What does `Qwen 7b, 14b & 72b` mean? Is the result of three size qwen model?
2. What is the meaning of x-axis?

**Comment by HYZ17** [comment]
1. Yes.
2. The x-axis is the Min-K% score.
