### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model

### ISSUE THREAD

**Issue by acylam** [hkust-nlp/llm-compression-intelligence#6]
Hi, during the `_prepare` step in `EvalDataset`, how do you deal with the case where a sample is longer than the `max_seq_len` of a model? I am running into this warning when trying to calculate BPC for some models with short max sequence lengths:

>Token indices sequence length is longer than the specified maximum sequence length for this model. Running this sequence through the model will result in indexing errors

Do you truncate the sample somehow like setting a `max_length` for `self.tokenizer.encode` or do you split the sample into chunks and encode each chunk?

**Comment by HYZ17** [comment]
Hello, you can ignore this warning. This warning comes from the tokenizer, indicating that the input sequence length exceeds the model's input length, but it does not affect the operation of the tokenizer. As mentioned in the paper, we use the sliding windows method during evaluation to ensure that the length of each input is less than the model's length limit. For more detail about sliding windows, please refer to [this blog](https://huggingface.co/docs/transformers/perplexity).

**Comment by acylam** [comment]
Make sense. Thanks for clearing this up.
