### ISSUE TITLE
[Feature] Added support for LLM Compression Evaluation at OpenCompass

### ISSUE THREAD

**Issue by acylam** [hkust-nlp/llm-compression-intelligence#7]
First of all, thank you for your hard work in developing this evaluation method!

We have now added support for the llm-compression dataset and Bits per Character calculation at OpenCompass. OpenCompass is a LLM evaluation platform, focused on the understanding of AGI, include Large Language Model and Multi-modality Model. It currently supports a wide range of models (LLaMA, LLaMa2, ChatGLM2, ChatGPT, Claude, etc) and over 80+ datasets.

After integrating your datasets into OpenCompass, it is now possible to perform LLM compression evaluation tasks for multiple models in parallel with minimal adjustments and configuration.

Head over to [OpenCompass](https://github.com/open-compass/opencompass) now to try it out for yourself! 

Demo configuration files for llm-compression evaluation:
- [Dataset config](https://github.com/open-compass/opencompass/tree/main/configs/datasets/llm_compression)
- [Evaluation config](https://github.com/open-compass/opencompass/blob/main/configs/eval_llm_compression.py)

Please provide any feedback and questions regarding our implementation and we welcome further collaboration to push the frontier of LLM evaluation in the open-source community.

**Comment by HYZ17** [comment]
Thank you for your support!

**Comment by tonysy** [comment]
@HYZ17 Hi, would you like to update the readme with this news? Hope the OpenCompass will improve the visibility of this great work.

**Comment by HYZ17** [comment]
Thank you for your support. The README has been updated. I have just finished testing the code and found some issues. 

Firstly, as mentioned [here](https://github.com/open-compass/opencompass?tab=readme-ov-file#-data-preparation), I downloaded data and found that the corpora for llm-compression is not in the data package yet, which caused the first error when running it. To fix it, I put the data in the corresponding folder. 

Secondly, the results differ from those in our paper. the command I used to run the tests is as follows: 
`CUDA_VISIBLE_DEVICES=1,2,3,4,5,6 python run.py --datasets llm_compression --hf-path huggyllama/llama-7b --model-kwargs use_flash_attention_2=True cache_dir="/ssddata/yuzhen/model_hub" device_map='auto' --tokenizer-kwargs cache_dir="/ssddata/yuzhen/model_hub" --batch-size 20 --num-gpus 1`
The tests were run on six A100-80G GPUs in the official environment. The results are as follows:

```
dataset	            version	   metric	    mode	    result
llm_compression-arxiv_math	        af04af	   bpc	unknown	     0.51
llm_compression-commoncrawl	af04af	   bpc	unknown	     7.07
llm_compression-python	         af04af	    bpc	unknown	     2.47
```
For the commoncrawl and python parts, the results differ significantly from those in our paper, but the results for arxiv_math are very close.  I noticed that the arxiv_math tests were not split and ran on a single thread, whereas the commoncrawl and python tests were run in parallel multi-threaded mode. Based on this, I believe there may be some issues in the result saving and summarizing part for multi-threaded tests, leading to incorrect final results. 

Therefore, I further debugged and noticed the following issues, which might help you identify the errors: 
1. The newly defined `LLMCompressionSummarizer` does not seem to be called correctly, and the `DefaultSummarizer` is still being used by default.
2. Even after forcibly switching to the `LLMCompressionSummarizer`, the results are still incorrect. However, I believe the Summarizer may not be the main problem (I am not sure). I suspect that the `SWCELossInferencer` may not be correctly saving the results, leading to incorrect outputs from the Summarizer. 

These are the issues I have found and some of my insights. I am happy to provide further help.

**Comment by HYZ17** [comment]
Additionally, I have a suggestion to improve the efficiency of testing. As I mentioned earlier, the arxiv_math tests are run on a single thread. This is primarily because the `SizePartitioner `called during task partitioning, by default, has a maximum sample size per task of 40,000. Compared to the other two tasks, arxiv_math has fewer samples, but each sample is longer. To enhance the efficiency of the arxiv_math tests and make full use of computing resources, I suggest redefining the `max_task_size` parameter of the `SizePartitioner`, similar to what is done [here](https://github.com/open-compass/opencompass/blob/main/configs/eval_chat_cibench.py#L87).

**Comment by acylam** [comment]
@HYZ17 Thank you for testing out the new feature. I have opened an issue at opencompass. Please see my comments in https://github.com/open-compass/opencompass/issues/1114
